### ISSUE TITLE
Warnings on client console

### ISSUE THREAD

**Issue by leite08** [mgscreativa/kurounin-pagination-react-example#1]
Hi! First, thank you for making this project available!

I've downloaded and run it as explained (`meteor npm install` && `meteor`) but I'm getting a lot of warnings on client side, as you can see on the attached image.

Mainly:

- Deprecation of `PropTypes` via the main React package
- Deprecation of `createClass` via the main React package
- Usage of `getDefaultProps` instead of the static property `defaultProps`

Tested on the Kurounin Pagination original project, there are no such warnings there.

Did an update (`meteor update`) do 1.6 but the warnings persisted.

Do you know how to fix it?

![warnings](https://user-images.githubusercontent.com/2132564/32782136-8d0f6220-c92e-11e7-94c4-caabea015b68.png)

**Comment by mgscreativa** [comment]
Hi! All related to packages! not related to my code.
- Usage of getDefaultProps instead of the static property defaultProps: https://github.com/adazzle/react-data-grid/issues/978

Anyway, if you find a better, new data grid for react please let me know, because react-data-grid development seems too slow...

**Comment by leite08** [comment]
Thank you!
